JSDocs for inline form
blackbaud/skyux-inline-form pull request #38
Opened 2020-09-14 01:31 UTC by blackbaud-johnly

2020-09-14 14:45 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-inline-form?_sp.spa=pr-jsdocs-091220](https://developer.blackbaud.com/skyux-inline-form?_sp.spa=pr-jsdocs-091220)

2020-09-14 15:27 UTC, Blackbaud-DeniseCisneros approved these changes, later dismissed

2020-09-14 15:54 UTC, Blackbaud-AlexKingman requested changes
Looks great, but we'll need to add `@internal` to `SkyInlineFormButtonAction` and `SkyInlineFormAdapterService `.

2020-09-15 13:32 UTC, Blackbaud-AlexKingman approved these changes

2020-09-15 13:44 UTC, blackbaud-ado commented
Preview build at [https://developer.blackbaud.com/skyux-inline-form?_sp.spa=pr-jsdocs-091220](https://developer.blackbaud.com/skyux-inline-form?_sp.spa=pr-jsdocs-091220)

2020-09-15 13:53 UTC, merged